name: rmdev_widgets
description: "A package to house all RMDEV's reusable widgets"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.16
  flutter_switch: ^0.3.2
  form_field_validator: ^1.1.0
  gap: ^3.0.1
  get: ^4.6.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  logger: ^2.2.0
  nb_utils: ^7.0.5
  pinput: ^5.0.0
  simple_shadow: ^0.3.1
  smart_auth: ^2.0.0
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

   assets:
     - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
