name: rmdev_widgets
description: "A package to house all RMDEV's reusable widgets"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_switch: ^0.3.2
  form_field_validator: ^1.1.0
  gap: ^3.0.1
  intl: ^0.18.1
  logger: ^2.2.0
  nb_utils: ^7.0.0
  simple_shadow: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
